# Site settings
permalink: /:year/:month/:title/
paginate: 5
title: anmonteiro
tagline: 'Code ramblings'
keywords: software,engineering,functional,programming
description: > # this means to ignore newlines until "baseurl:"
  I'm a Software Engineer with a passion for entrepreneurship and open-source
  software. This is where I write about software engineering, programming and
  lifestyle.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://anmonteiro.com" # the base hostname & protocol for your site

author:
  name: 'António Nuno Monteiro'
  email: anmonteiro[at]gmail.com
  twitter_username: anmonteiro90
  github_username:  anmonteiro
  linkedin_username: anmonteiro
  stackoverflow_username: anmonteiro

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
gems:
  - jekyll-paginate
  - jekyll-gist
