// Generated by Melange

import * as React from "react";
import * as Random from "melange/lib/es6/random.mjs";
import LayoutJs from "./layout.js";
import * as RescriptReactErrorBoundary from "@rescript/react/./src/RescriptReactErrorBoundary.bs.js";

var make = LayoutJs;

var Layout = {
  make: make
};

function $$default(param) {
  return React.createElement(RescriptReactErrorBoundary.make, {
              children: React.createElement(React.Suspense, {
                    children: React.createElement(make, {
                          children: React.createElement(param.Component, param.pageProps)
                        }),
                    fallback: "LOADING"
                  }),
              fallback: (function (param) {
                  var error = param.error;
                  console.log("error", error, error.message);
                  return React.createElement(React.Fragment, undefined, React.createElement("strong", undefined, "An error occurred"), React.createElement("pre", undefined, param.info.componentStack));
                })
            });
}

function init(param) {
  Random.init(Date.now() | 0);
}

Random.init(Date.now() | 0);

export {
  Layout ,
  $$default ,
  $$default as default,
  init ,
}
/* make Not a pure module */
