// Generated by Melange

import * as Caml_option from "melange/lib/es6/caml_option.mjs";

function makeProps(href, as_, prefetch, replace, shallow, passHref, children, param) {
  return {
          href: href,
          as: as_,
          prefetch: prefetch,
          replace: replace,
          shallow: shallow,
          passHref: passHref,
          children: children
        };
}

var Link = {
  makeProps: makeProps
};

var $$Error = {};

var Head = {};

var Events = {};

function push(t, as_, options, url) {
  t.push(url, as_ !== undefined ? Caml_option.valFromOption(as_) : undefined, options !== undefined ? Caml_option.valFromOption(options) : undefined);
}

function pushT(t, as_, options, t$p) {
  t.push(t$p, as_ !== undefined ? Caml_option.valFromOption(as_) : undefined, options !== undefined ? Caml_option.valFromOption(options) : undefined);
}

function replace(t, as_, options, url) {
  t.replace(url, as_ !== undefined ? Caml_option.valFromOption(as_) : undefined, options !== undefined ? Caml_option.valFromOption(options) : undefined);
}

function replaceT(t, as_, options, t$p) {
  t.replace(t$p, as_ !== undefined ? Caml_option.valFromOption(as_) : undefined, options !== undefined ? Caml_option.valFromOption(options) : undefined);
}

function prefetch(t, as_, url) {
  t.prefetch(url, as_ !== undefined ? Caml_option.valFromOption(as_) : undefined);
}

function prefetchT(t, as_, options, t$p) {
  t.prefetch(t$p, as_ !== undefined ? Caml_option.valFromOption(as_) : undefined, options !== undefined ? Caml_option.valFromOption(options) : undefined);
}

var Router = {
  Events: Events,
  push: push,
  pushT: pushT,
  replace: replace,
  replaceT: replaceT,
  prefetch: prefetch,
  prefetchT: prefetchT
};

var Config = {};

export {
  Link ,
  $$Error ,
  Head ,
  Router ,
  Config ,
}
/* No side effect */
